### ISSUE TITLE
Returning CustomAccount fields as claims

### ISSUE THREAD

**Issue by parkinsona** [thinktecture/Thinktecture.IdentityServer.v3.MembershipReboot#11]
Hi,

I'm currently using the following for membership reboot in idsvr3:

``` c#
 public class CustomUser : RelationalUserAccount
    {
        [Display(Name="First Name")]
        public virtual string FirstName { get; set; }
        [Display(Name = "Last Name")]
        public virtual string LastName { get; set; }
        
    }
```

In the MR database these are added as fields to the UserAccounts table.
By default, it doesn't look like these are returned as claims by identity server.
Is there a way to get them returned as claims without setting them up as claims, or should they be setup as claims to begin with?

**Comment by galenp** [comment]
For me... I've moved to pure claims for my member properties.  I think if
you can go that way it's easier.

**Comment by parkinsona** [comment]
I am able to switch them to pure claims. I'm curious to see if there is a way to return the UserAccount properties. If its not possible, then I'll switch over to pure claims.

**Comment by brockallen** [comment]
If you configure a `MapClaimsFromAccount<T>` command handler with the MR config then this will run when we issue claims.

**Comment by parkinsona** [comment]
I added the following, but it doesn't seem to be getting into the Handle method...

``` c#
 public class CustomClaimsMapper : ICommandHandler<MapClaimsFromAccount<CustomUserAccount>>
        {
            public void Handle(MapClaimsFromAccount<CustomUserAccount> cmd)
            {
                cmd.MappedClaims = new System.Security.Claims.Claim[]
    {
    new System.Security.Claims.Claim(ClaimTypes.GivenName, cmd.Account.FirstName),
    new System.Security.Claims.Claim(ClaimTypes.Surname, cmd.Account.LastName),
    };
            }
        }
```
``` c#
  public static MembershipRebootConfiguration<CustomUserAccount> config;
        static MembershipRebootUserServiceFactory()
        {
            config = new MembershipRebootConfiguration<CustomUserAccount>();

            //Add a handler for the Custom User Account Type
            config.AddCommandHandler(new CustomClaimsMapper());
        }
```

Not sure if there's something else I need to configure to get this working. Its not stepping into the handle at the moment, and therefore doesn't return the extra claims.

Am I missing another piece of config?

**Comment by brockallen** [comment]
This would only get called when a client is requesting a token (not just at login time). Did you test that flow?

I just re-tested it and it's working (but as I said, it's only called when a client requests a token).

**Comment by brockallen** [comment]
Also, I just updated the dev branch with the sample code.

**Comment by parkinsona** [comment]
I'm using the implicit client. I haven't tried resource owner flow where we explicitly request a token. I thought implicit client requested a token when you tried to access an authenticated page, or am I mistaken?

**Comment by brockallen** [comment]
Depends. If you're only getting an id_token, then yes. But if you're also getting an access token then no, unless you've configured the "include claims in token" on the scopes.

**Comment by parkinsona** [comment]
My RP has the following setup. So its only getting the id_token. 
``` c#
   ResponseType = "id_token",
    Scope = "openid email profile all_claims",
```

I've not changed the standard scopes setup.

**Comment by parkinsona** [comment]
I am using idsvr beta 3-3 at the moment, not sure if that will make a difference

**Comment by brockallen** [comment]
I think the map was added later than beta3-3. I was testing on the dev branch.

**Comment by parkinsona** [comment]
Well that would make some sense. I'll have a crack at using the latest beta and see how that goes.

**Comment by brockallen** [comment]
Alternatively you might consider the myget feed -- those are CI builds, so they're the most up to date.

**Comment by parkinsona** [comment]
I updated to beta 4-1 and this is now adding the claims as expected.

Thanks again for your help.
