### ISSUE TITLE
Building

### ISSUE THREAD

**Issue by dontbesorry80** [thinktecture/Thinktecture.IdentityServer.v3.MembershipReboot#12]
I'm struggling to see how this works. The solution doesn't seem to want to build. It can't seem to find some packages. So I just tried adding the project to my identity server v3 and also adding the extra files into my Host project and couldn't get it to build. Am I going about this the wring way? What's the simplest way to add MembershipReboot to my Identity Server?

**Comment by brockallen** [comment]
It will next week when we RC. We've been doing all of our work on the dev branch.

**Comment by dontbesorry80** [comment]
Ahh, I'll wait then. Looking forward to it!
