### ISSUE TITLE
Trouble Registering the Factory.

### ISSUE THREAD

**Issue by dontbesorry80** [thinktecture/Thinktecture.IdentityServer.v3.MembershipReboot#15]
In the sample code the configuration is:
```
appBuilder.Map("/admin", adminApp =>
{
	var factory = new Thinktecture.IdentityManager.Host.MembershipRebootIdentityManagerFactory("MembershipReboot");
	adminApp.UseIdentityManager(new Thinktecture.IdentityManager.IdentityManagerConfiguration()
	{
		IdentityManagerFactory = factory.Create
	});
});
```
However with the version of IdentityManager installed from nuGet this seems out dated. I tried the following but can't seem to get the ManagerOptions correct.
```
app.Map("/admin", adminApp =>
            {
                var factory = new Thinktecture.IdentityManager.Host.MembershipRebootIdentityManagerFactory("MembershipReboot");
                adminApp.UseIdentityManager(new Thinktecture.IdentityManager.Configuration.IdentityManagerOptions()
                {
                    Factory = factory.Create
                });
            });
```
Can you help? I would really like to get Membership Reboot working with my Identity Server v3 from NuGet.

Thanks in advance...

**Comment by brockallen** [comment]
On dev it's been updated. Check that and let me know.

**Comment by brockallen** [comment]
Any update?

**Comment by dontbesorry80** [comment]
So.. I have rebuilt my identity server from a blank projects and added the RC using nuGet. Then I got the dev version of your IdentityServer.MembershipReboot and added it into the project and..... It's WORKING.. Hoorah!

Now I just need to secure it.. I assume that after creating a user you can then update the OWIN Startup to push it back to the identityserver to login etc?

**Comment by brockallen** [comment]
Assuming they're both pointing tot he same DB, once a user is created in IdMgr, then should be able to login right away with IdSvr (if that's what you were asking).

**Comment by dontbesorry80** [comment]
What I was saying is the user management interface can now be accessed by
anyone. I would need to lock that down somehow..??

**Comment by brockallen** [comment]
Yes, you should. There are docs on that: 
https://github.com/thinktecture/Thinktecture.IdentityManager/wiki/Security-Configuration

**Comment by dontbesorry80** [comment]
Brilliant thanks! Loving your work. I'm not sure if I'm good enough to help
but if there is anything you need, please let me know. Testing or whatever.

Rob

**Comment by brockallen** [comment]
thanks.
